### ISSUE TITLE
не понял эту строку

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#11]
So in the case (not to guess) state of "+" is used to mark what search is needed.
как по рус?

**Comment by kvichans** [comment]
Поэтому в этом случае (чтобы избежать угадывания) используется состояние одно- или много-строчности для определения какой нужен поиск.

(Для re-паттерна я не смог подобрать анализ его текста, чтобы решить нужен ли многострочный поиск. Поэтому ФФ считает, что поиск многострочный, если контрол для паттерна многострочный)

**Comment by Alexey-T** [comment]
так
So in this case, to avoid guessing, plugin sees single-line / multi-line state, to detect which search is needed.

**Comment by kvichans** [comment]
ок
