### ISSUE TITLE
dlg Help needs 'ok' btn

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#16]
![Screenshot from 2019-08-24 18-39-48](https://user-images.githubusercontent.com/4154978/63639653-9ba62480-c69e-11e9-98fd-2b96c7ac2f19.png)

**Comment by kvichans** [comment]
Отказ.
Это претензия к *стилю*. Мне нравиться *минимально достаточный* стиль. 
- Кнопка для клика мышкой уже есть - крест в титуле.
- С клавиатуры работает `ESC`.
