### ISSUE TITLE
dlg 'presets' layout narrow

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#23]
![Screenshot from 2019-08-24 18-50-47](https://user-images.githubusercontent.com/4154978/63639766-23406300-c6a0-11e9-9e4a-d891cd88a781.png)

**Comment by Alexey-T** [comment]
+ need btn 'cancel'

**Comment by kvichans** [comment]
Попробуйте из ГХ

**Comment by Alexey-T** [comment]
layout not fixed . checks не влезают.

**Comment by kvichans** [comment]
нужен новый снимок

**Comment by Alexey-T** [comment]
![Screenshot from 2019-08-26 08-17-27](https://user-images.githubusercontent.com/4154978/63666785-f8f2c080-c7d9-11e9-8f3c-dd2d7faa1631.png)

**Comment by Alexey-T** [comment]
он такой же?

**Comment by kvichans** [comment]
да
странно

**Comment by kvichans** [comment]
Пробуйте
