### ISSUE TITLE
lang

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#25]
```
Engine option 
    "use_selection_on_start"
uses selected text from document for the field "Find what".
It can be replaced with using of macro var
    {ed:SelectedText}.
So you can use document selection many times but not only on start.
```
->
Instead of this option, you can use macro variable
  {...}
This way you can use selected text many times, not only at start.

**Comment by Alexey-T** [comment]
These folders should not be included in each other.
->
Folder names can be independent, ie not included into each other.

**Comment by Alexey-T** [comment]
The field also can contain folder(s) and <tabs> together.
->
Field can also contain both folder mask(s) and "<tabs>" macro.

**Comment by kvichans** [comment]
> Folder names can be independent

`can be` разве указывает на обязательность?

**Comment by Alexey-T** [comment]
"also can" неверно. надо "can also". "may also".

**Comment by kvichans** [comment]
Смысл нужно передать другой: папки **не** могут быть вложены друг в друга. Поиск просто не начнется

**Comment by Alexey-T** [comment]
тогда
Folder names must be independent, ie not included into each other.

**Comment by kvichans** [comment]
Спасибо
