### ISSUE TITLE
Col titles dont fit by width

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#28]
Win7 :)
![fif](https://user-images.githubusercontent.com/4154978/66269229-cb744a80-e84e-11e9-9a3b-4199ba1fcd0c.png)

**Comment by kvichans** [comment]
Я за это место не отвечаю - тут не срабатывает ваш autosize для ячеек статусбара
Извлечь repro?

**Comment by Alexey-T** [comment]
Не надо
