### ISSUE TITLE
Why so thin window title (toolwindow kind)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#29]
looks bad
![fif](https://user-images.githubusercontent.com/4154978/66269258-30c83b80-e84f-11e9-8b85-c13fa90a0ef3.png)

**Comment by Alexey-T** [comment]
example of OK title
![titleok](https://user-images.githubusercontent.com/4154978/66269277-610fda00-e84f-11e9-9e39-15c15891b1f6.png)

**Comment by kvichans** [comment]
Из трех кнпок в титуле для ФФ нужна только последняя.
Поэтому для `border` назначен стиль `DBORDER_TOOLSIZE`.
Кроме того, я не вижу нужды в *толстом* титуле, так как он есть полезное место.
