### ISSUE TITLE
Help en: inf commands

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files4#30]
There are three CudaText commands to start dialog:
    "Find in files" shows dialog only.
    "Find in current tab" shows dialog and also runs search if pattern has been set
(see engine option "use_selection_on_start").
    "Find by preset" shows list of suitable presets, shows dialog, fills fields 
by chosen preset and runs search. To be suitable preset needs to store:
    - pattern (or "use_selection_on_start" is on and selection is not empty),
    - mask of files,
    - start folder or/and tabs.

**Comment by Alexey-T** [comment]
тегайте мой ник чтобы я точно увидел. увидел т к я подписан на репо.

**Comment by Alexey-T** [comment]
Plugin provides 3 CudaText commands to display its dialog:
"Find in Files": just show dialog.
"Find in current tab": show dialog and also start the search, if pattern was set before. (.....)
"Find by preset": ask for a preset, then show dialog, filled from the chosen preset, and start the search. Those presets are allowed, which have stored:
...

**Comment by kvichans** [comment]
> start the search, if pattern was set before

Видимо моя формулировку ввела в заблуждение. Нужно сказать:
`"Find in current tab" показывает диалог и запускает поиск, если шаблон окажется определен (см ...)`

**Comment by Alexey-T** [comment]
"Find in current tab": show dialog and start the search, if text pattern is auto set (using the option ....)

**Comment by kvichans** [comment]
ок
