### ISSUE TITLE
No progressbar of search; cannot stop search by Esc

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#32]
Video
![fif4-bug](https://user-images.githubusercontent.com/4154978/71327185-76bfa200-2516-11ea-85bd-b3af386a04fc.gif)

конфиг тоже дам

**Comment by Alexey-T** [comment]
config
[cuda_fif4.zip](https://github.com/kvichans/cuda_find_in_files4/files/3992983/cuda_fif4.zip)

**Comment by kvichans** [comment]
1. Нужно содержимое консоли. 
2. Выйти из этого состояния: Shift+Click на [x] в титуле диалога

**Comment by Alexey-T** [comment]
консоль - никаких ошибок! но прогресса поиска нигде нет, и поля не заполняются, как будто завис- только можно нажать Esc и даже тогда оно не стопит.

**Comment by kvichans** [comment]
Буду разбираться

**Comment by Alexey-T** [comment]
folder c:\fpcupdeluxe -- get it. Download FpcUpDeluxe setup, in it - install Lazarus and FPC (2 button clicks, wait 10 min)

**Comment by Alexey-T** [comment]
Focupdeluxe не ставит ничего в ос- только ехе шники в папки

**Comment by kvichans** [comment]
Проверьте на версии из ГХ

**Comment by Alexey-T** [comment]
solved.
