### ISSUE TITLE
broken look of binary files' results in top editor

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#37]
on Linux
![Screenshot from 2020-04-29 18-40-26](https://user-images.githubusercontent.com/4154978/80616213-4dc19780-8a49-11ea-87a5-d8bf6039e6ad.png)

**Comment by kvichans** [comment]
Уточните, куда смотреть, чтобы увидеть проблему

**Comment by Alexey-T** [comment]
на вид hex symbols в редакторе

**Comment by kvichans** [comment]
Не понимаю. Я в плаге беру строки файла (двоичного) и наполняю ими editor-контрол. Где проблема?

**Comment by Alexey-T** [comment]
простой редактор: hex выглядят как xNN или xNNN
скриншот: hex в 1й строке где есть hex, выглядит не так

**Comment by kvichans** [comment]
В чем проблема, если он только "выглядит"? Как я могу что-то изменить?

**Comment by Alexey-T** [comment]
не знаю. закроем issue
