### ISSUE TITLE
cannot find whole-word '_('

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#40]
![Screenshot from 2020-10-27 19-41-17](https://user-images.githubusercontent.com/4154978/97333318-80c7d500-188c-11eb-99ea-9bef4c24ca27.png)

**Comment by kvichans** [comment]
Где проблема?

**Comment by Alexey-T** [comment]
FIF игнорит опцию whole-words. нашел  __init__(.

**Comment by kvichans** [comment]
Это задокументировано: если в шаблоне есть не_буквы, то опция игнорится
