### ISSUE TITLE
F4- "Replace with"-???

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#42]
нажатие Ф4 дает мелкий диалог поверх старого большого. (В котором нет поля "заменить на").
И как это юзать?
Почему не менять вид большого?
![Screenshot from 2020-11-06 18-55-55](https://user-images.githubusercontent.com/4154978/98386926-d86ef900-2061-11eb-9f7c-554da75974aa.png)

**Comment by Alexey-T** [comment]
В старом большом уже был какой-то поиск и он что то нашел. потом я жму ф4. и появился второй диалог поверх старого. А старый зачем висит?

**Comment by kvichans** [comment]
В "старом" - результы поиска
В "новом" нельзя поменять поиск, поэтому его результаты показывают что будет заменяться
