### ISSUE TITLE
FIF4 look on freebsd (GhostBSD) by default

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#45]
![fif_b](https://user-images.githubusercontent.com/4154978/103760106-b411a780-5025-11eb-9bd9-dfab25810450.png)

- caption of option-buttons - cropped (pls try bigger button height)
- too small dlg size
- unexpected tall Edit controls, look bad, they overlap

**Comment by Alexey-T** [comment]
@kvichans

**Comment by Alexey-T** [comment]
screen 2

![frt2](https://user-images.githubusercontent.com/4154978/103760520-4619b000-5026-11eb-97c1-1c8ed1eed477.png)

**Comment by Alexey-T** [comment]
after "adjust vertical controls" command in OptEditor

![fi2](https://user-images.githubusercontent.com/4154978/103760813-b6283600-5026-11eb-9df0-360911da4ef8.png)

**Comment by kvichans** [comment]
Попробуйте настройку `vertical_gap` увеличить
![image](https://user-images.githubusercontent.com/7419630/103765641-8da43a00-502e-11eb-823b-dce5e7318a7d.png)

**Comment by Alexey-T** [comment]
поменял 28 на 40, появился один зазор но не OK
![fif](https://user-images.githubusercontent.com/4154978/103766632-330bdd80-5030-11eb-825d-07b7a44a0ce8.png)

**Comment by Alexey-T** [comment]
вот alignments
![op](https://user-images.githubusercontent.com/4154978/103766709-59ca1400-5030-11eb-857c-652a7a4800bd.png)

**Comment by kvichans** [comment]
Выравнивания и так хорошие.
Про "только один зазор" - это ко мне. Разбираюсь

**Comment by Alexey-T** [comment]
@kvichans 
может поправите дефолтный размер формы?
по х - больше в 2 раза.
по у - больше в 1.2 раза
