### ISSUE TITLE
Error and plugin won't start

### ISSUE THREAD

**Issue by igorog** [kvichans/cuda_find_in_files4#47]
`Operating System: Arch Linux
Kernel Version: 5.10.8-arch1-1
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-3537U CPU @ 2.00GHz
Memory: 7.7 ГиБ of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

"pylib__linux" : "/usr/lib/libpython3.9.so.1.0"`

`Traceback (most recent call last):
  File "/home/ussr/.config/cudatext/py/cuda_find_in_files4/__init__.py", line 1, in <module>
    from .cd_fif4 import *
  File "/home/ussr/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 1745
    ),(*mn_i4op
       ^
SyntaxError: can't use starred expression here`

**Comment by Alexey-T** [comment]
- What version of CudaText?
- What version of OS Python?
- What steps did you do to see this?

**Comment by Alexey-T** [comment]
@kvichans
 Pls install Windows Python 3.9 and make the "Windows Python39 64bit" package for all to test

**Comment by igorog** [comment]
>     * What steps did you do to see this?

I just click any item in the comments menu

**Comment by Alexey-T** [comment]
Try again after fixing the user.json JSON format?

**Comment by igorog** [comment]
It didn't help here.
![screen1](https://user-images.githubusercontent.com/38178476/105157418-88bbac00-5b3f-11eb-8d6a-0dabaa3c7b22.png)

**Comment by Alexey-T** [comment]
Confirmed on Windows with Py3.9 package.

**Comment by Alexey-T** [comment]
@kvichans Fixed this by replacing `,(*smth )` to `,(*smth, )` .

FIF4 dialog is OK.
But new error! calling `=` menu shows new error. "cannot assign to tuple item".

**Comment by Alexey-T** [comment]
Temp solution:
reinstall plugin from this zip file
https://github.com/Alexey-T/cuda_find_in_files4/archive/patch-1.zip

**Comment by igorog** [comment]
> reinstall plugin from this zip file

Thank you, very much. This work fine!

**Comment by Alexey-T** [comment]
@kvichans Let's not close the topic, for future users.

**Comment by Alexey-T** [comment]
@kvichans Pls close, fixed.
