### ISSUE TITLE
crash with weird message!

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#49]
Pasted
\bMENU_(LIST|LIST_ALT|NO_FUZZY|NO_FULLFILTER|CENTERED|EDITORFONT)\b

 from editor, and got such text - see the EOL mark at end? it's pasted by OS

![Screenshot from 2021-02-06 12-53-27](https://user-images.githubusercontent.com/4154978/107114985-916bec00-687a-11eb-8e7c-a061ec9fa196.png)

on regex find-- got this
![Screenshot from 2021-02-06 12-53-19](https://user-images.githubusercontent.com/4154978/107114993-9cbf1780-687a-11eb-9a73-f2e91559f004.png)

```
Init: cuda_find_in_files4
Init: cudatext
[ 0.00"]Fif4D.work:2580 Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 2578, in work
    fifwork(m.observer, m.rslt, walkers, fragmer, frgfilters, m.reporter, rplc=rplc)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 3106, in fifwork
    for frgs in fragmer.provide_frag(body, build_new_body=(rplc!=RPLC_NO)):
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 4408, in provide_frag
    yield from walk_in_body(body)
  File "/home/user/.config/cudatext/py/cuda_find_in_files4/cd_fif4.py", line 4370, in walk_in_body
    lines       = body.splitlines()
AttributeError: '_io.TextIOWrapper' object has no attribute 'splitlines'
```

**Comment by Alexey-T** [comment]
(py 3.8)

**Comment by Alexey-T** [comment]
Pls fix! so I will support DMENU_nnn

**Comment by kvichans** [comment]
Как EOL попал в поле поиска?
Как это повторить?

**Comment by Alexey-T** [comment]
выделял всю строку в Куде. делал paste в это поле. в Линукс.
добавьте s=s.strip('\n') ,пишу по памяти.

**Comment by kvichans** [comment]
1. Не получается повторить копипастой в Вин
2. В слепую править опасно
3. Есть примерное понимание, как EOL портит работу. ToDo

**Comment by Alexey-T** [comment]
VirtualBox  у вас начал работать на ПК?

**Comment by kvichans** [comment]
Причину нашел. Дыра в логике.

Какое правильное/подходящее поведение в описанном случае: `[x]RegExp` и `EOL (\n) внутри строки`.
- Отказаться от поиска? Показать сообщение типа "Удалите EOL"
- Самому удалить EOL и запустить поиск?

**Comment by kvichans** [comment]
Решил отказаться от поиска с сообщением (в статусе) `Fix EOL in the field "Find"`

**Comment by kvichans** [comment]
Протестируйте, плз

**Comment by Alexey-T** [comment]
работает. спасибо.
