### ISSUE TITLE
(en) Control hints

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files4#5]
![image](https://user-images.githubusercontent.com/7419630/62206920-80940d80-b39b-11e9-8948-2dbacd93fe7d.png)
```
Multi-lines input
Ctrl+Enter for new line.
```
----
![image](https://user-images.githubusercontent.com/7419630/62207049-d23c9800-b39b-11e9-8709-e1382f9023df.png)
```
Show result line and both its nearest lines.
"-N+M" - N lines above and M lines below.
Switch on to set numbers.
```
----
![image](https://user-images.githubusercontent.com/7419630/62207121-0617bd80-b39c-11e9-83c4-f3c86a44e43a.png)
```
Extra options to find
See menu to change.
```
---
![image](https://user-images.githubusercontent.com/7419630/62207286-6eff3580-b39c-11e9-9987-6fb243808bfe.png)
```
Pattern to find. 
It can be multiline. EOL is shown as "§".
Use Shift+Enter to append "§" at pattern end.
Or switch to multiline mode ("+") to see/insert natural EOLs.
```
---
![image](https://user-images.githubusercontent.com/7419630/62207440-cf8e7280-b39c-11e9-950d-f20341616414.png)
```
Space-separated file or folder masks.'
Folder mask starts with "/".
Double-quote mask, which needs space-char.
Use ? for any character and * for any fragment.
Note: "*" matchs all names, "*.*" doesnt match all.
```
```
Always excluded:
   /.svn /.git /.hg /.idea /.cudatext
See engine option "always_not_in_files" to change.
```
---
![image](https://user-images.githubusercontent.com/7419630/62207619-4166bc00-b39d-11e9-9097-b4b02a9b46b7.png)
```
Start folder(s).
Space-separated folders.
Double-quote folder, which needs space-char.
~ is user Home folder.
$VAR or ${{VAR}} is environment variable.
<tabs> to search in tabs.
```
---
![image](https://user-images.githubusercontent.com/7419630/62207706-812da380-b39d-11e9-92e1-b83a98a6b740.png)
```
Click or Ctrl+B
   Choose folder.
Shift+Click or Ctrl+Shift+B
   Choose file to find in it.
```
----
![image](https://user-images.githubusercontent.com/7419630/62207783-b2a66f00-b39d-11e9-9a7d-ae95e7e88352.png)
```
How deep subfolders will be searched.
Use Ctrl+Up/Down to modify setting.
```

**Comment by Alexey-T** [comment]
- Multi-line input field. Ctrl+Enter: add new line.
- Show result line with its adjacent lines (above/below).
- Extra search options. Use popup menu to change.
- "multi-line"
- "less:" -> "Without:" - не надо короче, чтобы переводы влезали
- "matchs" -> "matches", "doesnt" -> "doesn't"
- "How deep subfolders will be searched." -> "How many folder levels to search."

**Comment by kvichans** [comment]
- `Multi-line input field. Ctrl+Enter: add new line.` 
DONE
- `Show result line with its adjacent lines (above/below).`
Фраза `Show result line and both its nearest lines` ваша, она из ФИФ
DONE
- Extra search options. Use popup menu to change.
DONE
- "multi-line"
DONE
- "less:" -> "Without:" - не надо короче, чтобы переводы влезали
DONE
- "matchs" -> "matches", "doesnt" -> "doesn't"
DONE
- "How deep subfolders will be searched." -> "How many folder levels to search."
DONE

**Comment by Alexey-T** [comment]
Закроем
