### ISSUE TITLE
'Replace with' don't work if called from = menu, but works if I press F4

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#50]
Из такого положения п-т 'replace-with' из = меню ничего не делает.  'emulate replace with' из = меню тоже.
hotkey F4 работает и дает мелкое окно вверху.

![Screenshot from 2021-02-06 15-47-29](https://user-images.githubusercontent.com/4154978/107118564-d0a63700-6892-11eb-88da-03875825a3ea.png)

**Comment by Alexey-T** [comment]
в консоли ничего.

**Comment by kvichans** [comment]
Есть повтор
ToDo

**Comment by kvichans** [comment]
Бета в ГХ

**Comment by Alexey-T** [comment]
работает.
