### ISSUE TITLE
Cannot replace regex to D$0 or D\0

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#51]
в Куд работает такая замена - в replace-with пишем $0 и это все что нашло regex.
`D$0`  это что нашло с буквой D.

В ФИФ это не идет!!
ни с $0 ни с \0.

было
![Screenshot from 2021-02-06 15-47-29](https://user-images.githubusercontent.com/4154978/107118712-9b4e1900-6893-11eb-999d-c7bf1216e790.png)

replace to `D$0`.
emulate replace дает

![Screenshot from 2021-02-06 15-52-40](https://user-images.githubusercontent.com/4154978/107118717-a4d78100-6893-11eb-93d6-bafa6922f530.png)

не могу сделать замены!!

**Comment by kvichans** [comment]
Нужен упрощенный повтор на тесте типа ABCD
Нужен снимок с диалогом Замена

**Comment by Alexey-T** [comment]
этот и так нормал. что упрощать? список слов в скобках?

**Comment by Alexey-T** [comment]
вот проще--замена regex
\b\a\w+
(все слова на букву A)
на 
D\0

**Comment by kvichans** [comment]
Есть репро. Работаю...

**Comment by kvichans** [comment]
Облом! С неожиданной стороны - Питон не умеет подставлять полное найденное выражение
`repr(re.sub(r'ab', r'X\0', 'abc'))` дает `'X\0c'`, а не `'Xabc'`

Увы :( 
Ищите обходные пути

**Comment by kvichans** [comment]
Нашлись добрые люди! Подсказали:
`=repr(re.sub(r'ab', r'X\g<0>', 'abc'))` дает ожидаемый результат.
Сделаю предобработку

**Comment by kvichans** [comment]
1. Будет работать с `\0`
2. Будет автоматом заменять `\0` на `\g<0>`. В том числе в контроле с текстом для замены
3. Будет подсказывать
![image](https://user-images.githubusercontent.com/7419630/107211829-21df3380-6a17-11eb-9e0a-aa67086da06d.png)

**Comment by Alexey-T** [comment]
спасибо! полезно. перевод-
```
Pattern to replace with.
To substitute regex groups: \1, \2...
To substitute the entire expression: \g<0> or \0
```
 'To use the entire found string: \g<0>

**Comment by kvichans** [comment]
Бета в ГХ

**Comment by Alexey-T** [comment]
работает.
