### ISSUE TITLE
'Replace' dlg pos

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#53]
![Screenshot from 2021-02-09 14-34-25](https://user-images.githubusercontent.com/4154978/107358082-00984900-6ae4-11eb-8926-ef78518018c2.png)

тут не очень видно,но у меня диалог "заменить"  (F4) рисуется как часть диалога ниже (где все опции).
на втором ПК тени нету от окна и там диалог выглядит как часть окна большого.

предлагаю- поместить мелкое окно (Ф4) правее+ниже на 20 пикс.
это решит еще одну проблему- на некоторых дистрах Лина мелкое окно рисуется СЗАДИ большого и его вообще НЕ ВИДНО. со смешением 20пкс его будет видно

**Comment by Alexey-T** [comment]
на втором ПК. уточняю-

- если вызвать по F4- мелкое окно - поверх 
- если вызвать его же но кликом из =-меню, мелкое окно кладется СЗАДИ.

не понимаю это АПИ баг или ваш?

**Comment by kvichans** [comment]
1. Опции от большого окна спрятаны специально. Все, которые влияют на замены, в мелком продублированы. Чего вы не видите в нем?
2. Очень интересно разовабраться чья тут вина. Взаимодействуют трое: большой диалог, меню и малый диалог.
Внутри реакции на хоткеи и пп.меню - это один код. Похоже на косяк АПИ

**Comment by Alexey-T** [comment]
не знаю что там в Лаз происходит. давайте сместим хотябы на +20 пкс.

**Comment by kvichans** [comment]
Дам настройку - каждый под себя сместит

**Comment by Alexey-T** [comment]
да, поднять годится.

**Comment by kvichans** [comment]
ToDo

**Comment by kvichans** [comment]
![image](https://user-images.githubusercontent.com/7419630/107487982-d1431400-6b97-11eb-96e0-d1b23c7d287e.png)
дает
![image](https://user-images.githubusercontent.com/7419630/107488050-e6b83e00-6b97-11eb-931b-9c3c111f9062.png)

Публиковать?

**Comment by Alexey-T** [comment]
- дефолт надо дать 20, не ноль, зачем вы заставляете людей по дефолту видеть баг Лаза?
- не 20 а лучше 30

**Comment by kvichans** [comment]
Умолчания == 0

**Comment by Alexey-T** [comment]
Чтобы люди не думали что в Лин ваш плагин завис

**Comment by Alexey-T** [comment]
и не +30, а -30, чтобы вверх было.

**Comment by Alexey-T** [comment]
@kvichans ?

**Comment by kvichans** [comment]
Мне не нравиться идея делать умолчательный сдвиг.
Косяк исправят, а дурное умолчание останется

**Comment by Alexey-T** [comment]
тогда мы не решим трабл. юзеры будут видеть баг.

**Comment by kvichans** [comment]
Пробема возникает (по вашим словам) только при одном из случаев использования.
Пусть не делают так.

**Comment by Alexey-T** [comment]
не делают вызов пунктов из = меню вышкой? ну да.
