### ISSUE TITLE
panels Results and Source have different gaps

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#54]
The panels Results and Source have different gaps.

![issue_fif4_gaps](https://user-images.githubusercontent.com/4154978/107754216-37fc3500-6d32-11eb-9086-e963c6a9b0ec.png)

**Comment by Alexey-T** [comment]
@kvichans 2nd report-- I solved it, u didn't apply fix?

**Comment by kvichans** [comment]
Ваш фикс мне не понравился

**Comment by Alexey-T** [comment]
@kvichans Can we fix it, or not needed?

**Comment by kvichans** [comment]
Не понимаю, где тут проблема
Эти панели заполнены с разными целями. 
Верхней не нужны номера строк - нижней обязательны

**Comment by Alexey-T** [comment]
OK, solved.
