### ISSUE TITLE
UI/ UX for search

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#55]
Я уже 10 секунд смотрю на окно -НЕ пойму что оно делает. то ли ищет то ли ничего не нашло и я могу работать. судя по "отмена работает" оно не нашло.
неудобно. надо индикаатор "мы закончили, нашли.... или не нашли"

![Screenshot from 2021-02-12 13-59-21](https://user-images.githubusercontent.com/4154978/107760435-c7a5e180-6d3a-11eb-9eb8-0825dea61a4a.png)

**Comment by kvichans** [comment]
Есть уже такой индикатор: время (самое правое поле с статус-строке)
В процессе работы показывается в круглых скобках

**Comment by Alexey-T** [comment]
можно добавить текст в верхний едитор- "No results were found"?

**Comment by Alexey-T** [comment]
вариант 2.
"время" там - показать как

-  Working: ### при поиска
- Completed: ### когда всё
