### ISSUE TITLE
How to show dialog field 'not in files'/'exclude files'?

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#56]
Нужно это поле. не найду его. в большом длг опций нашел

always_not_in_files

значит поле ГДЕ ТО есть?

**Comment by kvichans** [comment]
Нет, это значение добавляет из настроек в начале самого поиска. Кроме настроек нигде не отображается

**Comment by kvichans** [comment]
Точнее можно не ходить с настройки, а посмотреь значение в тултипе над `Ex:`
