### ISSUE TITLE
Smthing is broken with resizing of results after search, bottom editor is out of view

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#57]
[Screencast 2021-02-12 14:10:47.zip](https://github.com/kvichans/cuda_find_in_files4/files/5971319/Screencast.2021-02-12.14.10.47.zip)

**Comment by kvichans** [comment]
Передайте настройки ФФ4

**Comment by Alexey-T** [comment]
[settings.zip](https://github.com/kvichans/cuda_find_in_files4/files/5973982/settings.zip)

**Comment by kvichans** [comment]
Подтверждаю
Минимальная высота диалога не согласована с высотами Результы+Исходник
ToDo
