### ISSUE TITLE
bad msg about Replace-all

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#58]
'Replace in all files/tabs?'
пугает- оно что, в ТАБАХ меняет еще? нет 
лучше
'Replace in all found files?'

**Comment by kvichans** [comment]
Параметры поиска устроены так, что можно искать в нескольких "корнях"
Одним из "корней" может быть "в табах"
Поэтому для "поисковика" файлы и табы не различаются
