### ISSUE TITLE
small UI issue

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#62]
предлагаю вместо 'Ex'  писать полное слово 'Exclude:",
на скрине я написал его выше лабела, видно
как нужно раздвинуть контролы.
Зачем- слово Ex не говорит ничего, и я забывал 2 раза где искать опцию exclude.
![la](https://user-images.githubusercontent.com/4154978/110691219-f017e300-81f5-11eb-870e-2f323eba37ad.png)

кнопка "..." тоже раздвинется. это ОК.

**Comment by kvichans** [comment]
Я брал из словаря
![image](https://user-images.githubusercontent.com/7419630/110823347-1051ab80-82a3-11eb-977f-1ebf5c5ab326.png)

Мне не нравится `Exclude` - он слишком длинный, диалог будет рыхлый
`But` подойдет?

**Comment by Alexey-T** [comment]
But не подойдет. не технический термин ИМХО. except подойдет.

**Comment by kvichans** [comment]
У `Except` лишь на один символ меньше `Exclude` - это много

**Comment by kvichans** [comment]
Приму любой из 4 букв

**Comment by Alexey-T** [comment]
'Skip'

**Comment by kvichans** [comment]
Я за. Делать?

**Comment by Alexey-T** [comment]
да. но лучше Except, для Ру или Гер перевода надо.

**Comment by kvichans** [comment]
Перевод-то тут причем? Пусть сами подбирают короткие термины. ФФ все переварит

**Comment by kvichans** [comment]
На моей платформе получается так
![image](https://user-images.githubusercontent.com/7419630/110828820-7f7dce80-82a8-11eb-9ec0-4f6936337dd9.png)

**Comment by Alexey-T** [comment]
да, ОК
