### ISSUE TITLE
how to close the source panel

### ISSUE THREAD

**Issue by Jzhenli** [kvichans/cuda_find_in_files4#64]
when the file is too big(>100M), it will be very slow to show the file in source panel. Not sure if have option to close it.

**Comment by Alexey-T** [comment]
Options / Settings-plugins / FindInFiles4, it has few options for file sizes--

![Screenshot from 2021-05-13 18-10-06](https://user-images.githubusercontent.com/4154978/118145720-8fd03800-b416-11eb-9e0c-3e91cb959e0f.png)

**Comment by Jzhenli** [comment]
@Alexey-T thanks for your reply.

If it's possible to close it, seems it will show hex file when the file is too big.  Besides, I don't think the source panel is necessary, since we always can read it by cudatext, here to show the search result is enough.

**Comment by Alexey-T** [comment]
sorry but I cannot get the idea: what do you suggest.

**Comment by Jzhenli** [comment]
![image](https://user-images.githubusercontent.com/42105688/118581166-bbab3f00-b7c3-11eb-902a-83ce8f165ff4.png)



@Alexey-T  Don't want this source panel as picture above shows.

**Comment by Alexey-T** [comment]
@kvichans

**Comment by kvichans** [comment]
@Jzhenli 
I also don't understand what you to want.
Did you try to set mentioned opt `dont_show_file_size_more(Kb)` to `0`?
