### ISSUE TITLE
wrong syntax highlights in the top panel

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#66]
![Screenshot from 2021-07-09 20-13-22](https://user-images.githubusercontent.com/4154978/125114130-37ee3e80-e0f2-11eb-9a2d-4a4a81022c5b.png)

это я ищу в папке kk которая есть все ваши распакованные плагины в отд-е папки.
видно 2 сбоя покраски - 

	<plugin.FindInFiles-v4_py35/cd_kv_dlg.py>: #17

и

		<1492>:                   app.menu_proc(mid_prn, app.MENU_ADD, caption=it['cap'])

**Comment by kvichans** [comment]
Какие установки и у этих настроек?:
![image](https://user-images.githubusercontent.com/7419630/125175224-5710cd00-e1d3-11eb-98bb-d66aa79f8107.png)

**Comment by Alexey-T** [comment]
All opts

![Screenshot from 2021-07-10 23-12-44](https://user-images.githubusercontent.com/4154978/125175419-9ee42400-e1d4-11eb-91fb-ca406fd857d7.png)

**Comment by kvichans** [comment]
Нет идей :(
А что показывается в табе, если перенести такой командой
![image](https://user-images.githubusercontent.com/7419630/125274254-75331600-e316-11eb-97b1-5bdcdbd01a7a.png)
после правого клика над Результатами?

**Comment by Alexey-T** [comment]
пока нет повтора. будет- проверю.
