### ISSUE TITLE
typo in id: MENU_, need DMENU_

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#67]
![Screenshot from 2022-01-15 14-53-26](https://user-images.githubusercontent.com/4154978/149620845-cc5b3a49-1117-4b10-86d9-fb73a2ea6af3.png)

**Comment by Alexey-T** [comment]
@kvichans

**Comment by kvichans** [comment]
Уже исправлено. В zip это место выглядит так
![image](https://user-images.githubusercontent.com/7419630/149726993-a64999e3-7f87-4ec0-8aa9-f984477373a4.png)
