### ISSUE TITLE
non-modal dialog will be better

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#70]
from forum

>Плагин открывается в модальном окне, нельзя параллельно работать в редакторе, это неудобно.
Чтобы перейти в редактор, приходится закрывать плагин, а чтобы вернуться к поиску, нужно опять открывать через меню Plugins.

http://synwrite.sourceforge.net/forums/viewtopic.php?f=6&t=2624&start=10

**Comment by Alexey-T** [comment]
declined by author

**Comment by d0vgan** [comment]
Why was it declined?

Actually, the plugin's file "cd_kv_dlg.py" contains this line:
```
def show(self, on_exit=None, modal=True, onetime=True):
```
If this line is changed to:
```
def show(self, on_exit=None, modal=False, onetime=True):
```
then the dialog is opened as a non-modal one.
However, if I press F4 in the non-modal dialog, then the Replace dialog appears _below_ the main dialog. I'm not aware of how the Replace dialog is invoked in the plugin and don't know how to fix that.

**Comment by Alexey-T** [comment]
author, ie @kvichans , told me in private mail - he needs that FIF dialog is modal. must have. because FIF requires(!) the same state of editor at the end of the search, and later.

**Comment by jackusay** [comment]
Do anyone know what will happen if you use `m.ag.show(on_exit=m.on_exit, onetime=False, modal=False)`?
In my simple test, nothing wrong.

**Comment by Alexey-T** [comment]
As I wrote, FIF requires the same state of editor before the search/ after the search. With non modal dialog user can violate this. Try to change the editor state- after the dialog shows, like set of opened files, text of files, group-mode.

**Comment by d0vgan** [comment]
Actually I've been using the `modal=False` from the beginning of March and have not noticed anything wrong.

**Comment by Alexey-T** [comment]
You didn’t see anything wrong —yet—. Author repeated in private mail- non-modal flag will give problems

**Comment by d0vgan** [comment]
Looks like a test case is needed for this :) Maybe a step-by-step guide of what to do to reproduce a problem.
