### ISSUE TITLE
How to Go-to-fragments if search results are in normal editor-tab?

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#72]
сделал поиск. перенес ответы в обычный таб.
теперь не пойму как сделать "перейти к фрагменту" для каждого фрагмента? пробовал 'go to definition'-  дает ошибку 'no go-to-definition plugins for this lexer'.
![fif1](https://user-images.githubusercontent.com/4154978/165627206-dd322761-51bd-4199-b60f-610cd883c013.png)

@kvichans

**Comment by kvichans** [comment]
Да, это было одно из проектных решений при переходе от ФиФ3 к ФиФ4: из таба уже нет команд. 
Нет этого и в планах.

**Comment by Alexey-T** [comment]
а почему нет в планах? трудно рааспарсить файл вам?

**Comment by kvichans** [comment]
Да, у ФиФ3 был жесткий формат. А ФиФ4 много гибкости. В диалоге не парсинг, а внутренние данные

**Comment by Alexey-T** [comment]
а когда данные (отчет) скинуты в file-tab, оттуда почему нет "прыжков к фрагментам"? удобно ж!

**Comment by kvichans** [comment]
Не понял! Чем последний вопрос отличается от исходного?

**Comment by Alexey-T** [comment]
вопрос - точнее просьба  - вернуть "прыжок" из file-tab. нет в планах?

**Comment by kvichans** [comment]
Нет. В ближайших точно нет. Дальше посмотрим, так как польза очевидна.
