### ISSUE TITLE
The input field is cleared after clicking the Find button

### ISSUE THREAD

**Issue by mix-7** [kvichans/cuda_find_in_files4#78]
Ввожу строку в поле поиска, нажимаю Find, поле поиска при этом очищается, приходится вводить еще раз (или выбирать из истории).
В общем, только со 2 раза можно начать поиск.

(CudaText 1.209.0.2, linux-x86_64-qt5, fpc 3.2.3
Ubuntu 23.10 Gnome 45.2 ядро Linux 6.5.0-15-generic)

**Comment by Alexey-T** [comment]
спасибо, за репорт. это уже было поправлено в лазарусе. это проблема не ФИФ а лазаруса.

**Comment by mix-7** [comment]
Пожалуйста.
Каким образом этот фикс попадет ФИФ?
Через обновление плагина ФИФ?

**Comment by Alexey-T** [comment]
решено уже в феврале. в новой Куд должно работать хорошо. закрываю.
