### ISSUE TITLE
Unable to insert character '|' in the input field

### ISSUE THREAD

**Issue by mix-7** [kvichans/cuda_find_in_files4#79]
Невозможно вставить символ '|' в во все поля FiF4 - Find, Files, From

Пробовал искать по регулярному выражению 'слово1 слово2 | слово2 слово1'
Символ '|' не ввести.

Как временный выход - копировать из другого редкатора (CudaText модально "закрыт" окном FiF4)

**Comment by Alexey-T** [comment]
у меня в убунту 20.х работает.

![Screenshot from 2024-03-04 15-30-18](https://github.com/kvichans/cuda_find_in_files4/assets/4154978/d2dec0c6-106d-4fbe-954c-79b6dcc3f6b6)

**Comment by mix-7** [comment]
P.S.

Извините, нк указал:

(CudaText 1.210.0.0, linux-x86_64-qt5, fpc 3.2.3
Ubuntu 23.10 Gnome 45.2 ядро Linux 6.5.0-21-generic)

**Comment by mix-7** [comment]
[То же и для CudaText](url=https://synwrite.sourceforge.net/forums/viewtopic.php?p=18935#p18935)

**Comment by Alexey-T** [comment]
баг Лазарус. буду писать жалобу.

**Comment by Alexey-T** [comment]
точнее и мой баг тоже. поправил его. в лазарусе тоже не гут, но я обошел это в Куд.

**Comment by mix-7** [comment]
В FiF4 4.8.15 в
CudaText 1.210.5.0, linux-x86_64-qt5, fpc 3.2.3
в Ubuntu 23.10 Gnome 45.2 ядро Linux 6.5.0-25-generic 
исправлено, ввод | работает, закрываю Issue.
Спасибо!
