### ISSUE TITLE
Close search dialog while the replace dialog opened, will prompt a error "TFormDummy Can not focus".

### ISSUE THREAD

**Issue by zangloo** [kvichans/cuda_find_in_files4#87]
Version: CudaText 1.214.7.2, linux-x86_64-gtk2, fpc 3.2.3
Steps:
1. Open search dialog
2. press F4 to open replace dialog
3. Using mouse to click the close buttom of the search dialog 
4. Using mouse to click the close buttom of the replace dialog 

will popup a message box with text below:
[TCustomForm.SetFocus] :TFormDummy Can not focus.

Press OK to ignore and risk data corruption.
Press Abort to kill the program.

![Screenshot_2024-06-16_20-11-12](https://github.com/kvichans/cuda_find_in_files4/assets/10681694/6c09c06c-1eee-419e-8f3d-53f9efc0f0cc)

**Comment by Alexey-T** [comment]
Confimed on linux-gtk2 version.
First I must close search dlg (in the background), then close replace dialog (small dlg on foreground).

**Comment by Alexey-T** [comment]
it is not plugin's bug, it is issue of Cud API  where OS can close the 'disabled' dlg. (background Srch dlg is disabled.)
