### ISSUE TITLE
rename opt not_show_file_size_more(Kb)

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_find_in_files4#9]
use word "hide", not "not show" or "do not show"

**Comment by kvichans** [comment]
`hide` не подходит - речь идет о блокировке *загрузки исходника* в нижнюю панель
Варианты:
- `block_show_file_size_more(Kb)`
- `dont_show_file_size_more(Kb)`

**Comment by Alexey-T** [comment]
Don’t show- ok

**Comment by kvichans** [comment]
ок - `dont_show_file_size_more(Kb)`
